### ISSUE TITLE
'Encoding::UndefinedConversionError ("\x89" from ASCII-8BIT to UTF-8)' with latest version

### ISSUE THREAD

**Issue by themilkman** [wvanbergen/chunky_png#105]
Hi,

with version 1.3.5 I get the following exception:
Encoding::UndefinedConversionError ("\x89" from ASCII-8BIT to UTF-8)

I am using chunky with rqrcode. With version 1.3.4 I do not have this issue. Because of that I open the issue here.

I am doing smth. like this:
```File.open(tmp_file.path, 'w') {|f| f.write barcode.to_png(height: 200, margin: 25, xdim: 100) }```

Is there smth. I have to change in my code? Pending further notice I stick to v 1.3.4.

Cheers and thanks for your work!

**Comment by wvanbergen** [comment]
Is it possible to get a full stack trace so I can see where exactly this exception occurs?

My best guess is that [this commit](https://github.com/wvanbergen/chunky_png/commit/afc1918d911d71a802142800d085742ac5763f36) introduced the issue.

**Comment by themilkman** [comment]
Hi @wvanbergen,
unfortunately I do not get a better trace, sorry. 

But your guess seems right, I uncommented the line in chunky 1.3.5 and it worked again as expected...

Cheers

**Comment by tweksteen** [comment]
Please do not reverse afc1918, this is the correct way of doing things. The problem is in your own code:

`barcode.to_png` returns a binary blob (ASCII-8BIT) as expected. And you are trying to save that into a file. The issue is that the default file opener uses UTF-8 for the encoding. You need to tell it to open it as a binary: `File.open(tmp_file.path, 'wb')`.

**Comment by themilkman** [comment]
@tweksteen is absolutely right, this was my mistake - with 'wb' it works as expected. Anyway, I guess this would be worth of a note in the changelog. Thanks for all your responses!
