### ISSUE TITLE
NameError: uninitialized constant ChunkyPNG::Encoding where EMPTY_BYTEARRAY = "".force_encoding(Encoding::BINARY).freeze was changed from EMPTY_BYTEARRAY = force_binary(String.new).freeze

### ISSUE THREAD

**Issue by john-rice** [wvanbergen/chunky_png#145]
Looking into what is causing an issue in compass-0.12.2 as of  chunky_png-1.3.12

NameError: uninitialized constant ChunkyPNG::Encoding
`EMPTY_BYTEARRAY = "".force_encoding(Encoding::BINARY).freeze` 
This was changed from `EMPTY_BYTEARRAY = force_binary(String.new).freeze` in chunky_png-1.3.12

https://github.com/wvanbergen/chunky_png/compare/v1.3.11...v1.3.12#diff-2cdfc6de147456ac90ecafcb70bcb99bR145

This code is occurring via compass-0.12.2

**Comment by wvanbergen** [comment]
It's likely due to this change: https://github.com/wvanbergen/chunky_png/commit/bb62069e144e5dff3f3ee1f772f6b649758258c6

I am assuming you are using Ruby 1.8, or JRuby in 1.8 mode.  This change removed some compatibility helpers we had in place for Ruby 1.8. Because Ruby 1.8 has not been supported for a very long time, I am not inclined to revert it.

You can ping to an older version in your Gemfile, or upgrade Ruby in your application.
