### ISSUE TITLE
When resize a png with square block, it's changed

### ISSUE THREAD

**Issue by snails** [wvanbergen/chunky_png#82]
I have a image that with qrcode, when I resize and zoom in, I find that it changes and lower the recognition capability.
Origin:
![qr](https://cloud.githubusercontent.com/assets/720285/6146110/1ab04aba-b224-11e4-8e85-b78ecd61f91c.png)
Resized:
![hello](https://cloud.githubusercontent.com/assets/720285/6146117/2979740e-b224-11e4-92d1-60fa32a2884d.png)

**Comment by wvanbergen** [comment]
Scaling down small images always has the risk of deformations, so it's always best to generate these kinds of images in the right size instead of resizing it afterwards.

Having said that, ChunkyPNG has two resize algorithms: nearest neighbor and bilinear. Nearest neighbor is the default;  maybe bilinear has better results for you? Try `image.resize_bilinear(width, height)`
