### ISSUE TITLE
Does it supports setting the DPI of an png before export

### ISSUE THREAD

**Issue by polarlights** [wvanbergen/chunky_png#87]
Thanks for your greate gem. Recently I met a problem, that I create a png image, its dpi is 72 dpi by default. However my printer is 300dpi. The image printed was somehow blur because of its dpi. 
I'm wonder does this gem support changing or setting its dpi?
Thanks a lot.

**Comment by wvanbergen** [comment]
Not really; the PNG format only deals with pixels, and is not necessarily** aware of how big these pixels will be. So, in order to get a higher resolution, you basically have to create an image with more pixels. In this case, `(current_width / 72) * 300` should be what you want.

** I think the PNG format allows you to provide the physical dimensions of the image as metadata. This is optional information and the viewer is allowed to ignore it. I think ChunkyPNG allows you to set this, but I don'r know the details around this anymore. You may need to dig into the PNG spec.

**Comment by polarlights** [comment]
Thanks for your answer. Now I am digging into it. When I am done with it, I will raise a PR.

**Comment by k2m30** [comment]
@wvanbergen You are not correct. According to the standard, you have a physical size of a pixel. The purpose of it is to know a real physical size of an image printed. 

The image itself is a grid of pixels with no inherent physical size, but the DPI value expresses an intended physical size. For example, an image that's 144 pixels wide with a DPI of 144 should appear one inch wide when displayed/printed, but an image that's 144 pixels wide with a DPI of 72 should appear two inches wide when displayed/printed.

The real problem appears with relatively small images like 1x1 inch. With a small resolution of 72 DPI you'll see no smooth lines, but ugly pixels. That is why 2520 DPI printers exist.

https://www.w3.org/TR/2003/PR-PNG-20030520/#11pHYs 

All in all, dpix/dpiy and/or ppux/ppuy setters with saving it to a file are appreciated.
