### ISSUE TITLE
Dependency on RMagick is unclear

### ISSUE THREAD

**Issue by chrisseaton** [wvanbergen/chunky_png#90]
Chunky PNG seems to have a dependency on RMagick in https://github.com/wvanbergen/chunky_png/blob/master/lib/chunky_png/rmagick.rb#L1. It's also used in the specs https://github.com/wvanbergen/chunky_png/blob/master/spec/chunky_png/rmagick_spec.rb.

However I can't find any dependency on it in the gemspec. When I bundle install it doesn't appear in the Gemfile.lcok either.

**Comment by wvanbergen** [comment]
This is by design - I don't want RMagick to be installed when people install ChunkyPNG.  Many people use ChunkyPNG especially because they don't need RMagick anymore.

The `chunky_png/rmagick` file is included to make interoperability between the two libraries easier. It is not `require`d by default, and people that use it should already have RMagick in them Gemfile.

Potentially we should add it as a development dependency to the gemspec so we can run the interoperability specs as part of the test runs,. but this is not a high priority for me.

**Comment by chrisseaton** [comment]
You could install RMagick on Travis before you run there - otherwise these specs aren't being in CI are they?

**Comment by wvanbergen** [comment]
Yup, that would be a nice improvement for the test setup. :+1:
