### ISSUE TITLE
Couldn't read 8 bytes from IO stream

### ISSUE THREAD

**Issue by ebds** [wvanbergen/chunky_png#96]
I have researched a bit about this error message, but haven't found anything.

When using compass I get those error messages:

![error_chunky](https://cloud.githubusercontent.com/assets/12143023/9224047/d4574670-40ff-11e5-90a4-834d573b7e4d.png)

I don't know what this means... any help appreciated

**Comment by wvanbergen** [comment]
My guess is that you have a PNG file that is less than 8 bytes (which by definition means it is an invalid image, but the error message is not very useful here).

**Comment by wvanbergen** [comment]
Actually, disregard that. It looks like it is some kind of damaged PNG file that is being included in your SCSS. Most likely a file that was improperly truncated for some reason.

Unfortunately, Compass doesn't tell you what file is causing the issue - that is something that should be fixed in Compass though.

**Comment by wvanbergen** [comment]
If you manage to find out what file triggers this, I can look into it a bit more to see what is wrong with it.

**Comment by whoisjake** [comment]
I found one!
![block](https://cloud.githubusercontent.com/assets/2079/15969970/fa8af65c-2ef7-11e6-8811-a7a15d2663f6.png)

**Comment by whoisjake** [comment]
I created it with http://www.piskelapp.com/

**Comment by wvanbergen** [comment]
The problem with this image is that it has 2 null-bytes after the final IEND chunk. So it doesn't conform to the PNG standard, and will fail when it tries to read a chunk from the remaining data.

Even though this image is technically invalid, I think the library should stop reading a stream once it hits the IEND chunk, instead of reading until it hits EOF, which should fix this problem.

**Comment by wvanbergen** [comment]
The fix has been merged!
